# Generated by Django 3.1 on 2020-08-27 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('favorite', models.BooleanField(default=False)),
                ('watch', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('users_proxies', models.ManyToManyField(through='buttons.ButtonBox', to='buttons.UserProxy')),
            ],
        ),
        migrations.AddField(
            model_name='buttonbox',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buttons.movie'),
        ),
        migrations.AddField(
            model_name='buttonbox',
            name='userproxy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buttons.userproxy'),
        ),
    ]
