# Generated by Django 3.1 on 2020-08-27 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buttons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttonbox',
            name='userproxy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='users_proxies',
            field=models.ManyToManyField(through='buttons.ButtonBox', to=settings.AUTH_USER_MODEL),
        ),
    ]
