# Generated by Django 3.1 on 2020-08-27 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buttons', '0002_auto_20200827_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buttonbox',
            old_name='userproxy',
            new_name='user',
        ),
    ]
